Add SBT devrun command to readme
guardian/contributions-frontend pull request #137
Opened 2016-09-20 13:27 UTC by desbo

A minor fix, but actually quite an important step in running locally.

2016-09-20 14:20 UTC, alexduf commented
I think it's a good idea, but I would add that a bit lower in the "Run" section. Something saying if you want to run it manually blahblah ?

2016-09-20 15:02 UTC, desbo commented
Good call, I've reshuffled things a bit in the readme

2016-09-20 15:09 UTC, AWare commented on README.md
> +sbt devrun
./start-frontend.sh?

2016-09-20 15:11 UTC, AWare commented on README.md
> +This runs [webpack-dev-server](https://webpack.github.io/docs/webpack-dev-server.html) on port 7777, proxying requests to 9111. In this case, the bundled JS is stored in memory, which allows for much
This approach doesn't have ssl, which will be more important when we do more on the thank you page as that breaks play sessions. There's a little work remaining to properly proxy this securely, but if you add giraffe.thegulocal.com to HOSTS it mostly works.

2016-09-20 15:12 UTC, AWare requested changes

2016-09-20 15:44 UTC, alexduf commented on README.md
> +This runs [webpack-dev-server](https://webpack.github.io/docs/webpack-dev-server.html) on port 7777, proxying requests to 9111. In this case, the bundled JS is stored in memory, which allows for much
yeah I think there's a broader conversation to have on how to start the dev server now we have webpack.
Could that be integrated with sbt? or should we have a local architecture with Ngninx -> webpack -> play ?

2016-09-20 16:40 UTC, desbo commented on README.md
> +sbt devrun
look 10 lines up

2016-09-20 16:47 UTC, desbo commented on README.md
> +This runs [webpack-dev-server](https://webpack.github.io/docs/webpack-dev-server.html) on port 7777, proxying requests to 9111. In this case, the bundled JS is stored in memory, which allows for much
Yeah, it seems a little confusing that there's nginx hosts for `contribute.thegulocal.com` and `giraffe.thegulocal.com`. We should rework how we run things locally for sure, and also tidy up the nginx config and decide on one hostname to use for development – that'll give us a much cleaner environment to document.

2016-09-20 17:53 UTC, AWare commented on README.md
> +sbt devrun
My bad. Sorry.

2016-09-22 10:44 UTC, desbo commented
I'm going to close this because I think there's a fair bit more work to do with the dev workflow, so we might as well re-do the docs at the same time as that.

2016-09-22 10:44 UTC, closed without merging