Paypal marketing opt in
guardian/contributions-frontend pull request #140
Opened 2016-09-20 16:28 UTC by pvighi

Added a post payment step when paying with PayPal that shows the option to sign in for marketing emails.

Some notes:
- The "post payment" page looks like the contribute page but it's a new page.All common parts have been extracted to a fragment named "contributionsMain" (worst name ever).
- To avoid any problems the post payment page will expect the email of the user to be in the play session.

2016-09-20 16:33 UTC, pvighi commented
![postpayment](https://cloud.githubusercontent.com/assets/15324270/18679616/5972543e-7f58-11e6-99f7-236a8b8e28d4.jpg)

2016-09-21 10:29 UTC, alexduf commented on app/controllers/PaypalController.scala
> +  def updateMetadata(countryGroup: CountryGroup) = NoCacheAction.async { implicit request =>
If you want to use a form I believe you can use `NoCacheAction(parse.form(metadataUpdateForm))` and then you don't have to do the `bindFromRequest`.

2016-09-21 10:30 UTC, alexduf commented on app/controllers/Redirect.scala
> +trait Redirect {self: Controller =>
spacing! :fearful: 

`trait Redirect { self: Controller =>`
or
```
trait Redirect {
  self: Controller =>
```

2016-09-21 10:31 UTC, alexduf commented on app/controllers/Redirect.scala
> +    val QueryParamsToForward = Set("INTCMP", "CMP") ++ additionalParams
`QueryParamsToForward` => `queryParamsToForward`

2016-09-21 10:32 UTC, alexduf commented on app/services/PaypalService.scala
> +  case class SavedContribution(contributionMetaData: ContributionMetaData, contributor: Contributor)
that should go in the `models` packages

2016-09-21 10:36 UTC, alexduf commented on assets/stylesheets/giraffe-react.scss
> +    width:40px;
spacing :fearful:

2016-09-21 10:36 UTC, alexduf requested changes
Sorry I got a bit pedantic on this one but I'm afraid there's a couple of things to fix here

2016-09-21 10:36 UTC, alexduf commented on app/controllers/PaypalController.scala
> +            Logger.error("No email returned from Paypal payment execution, skipping to thank you page")
I think you should log the payment ID here

2016-09-21 12:56 UTC, pvighi commented
new design:
![newpostpay](https://cloud.githubusercontent.com/assets/15324270/18711717/255de52c-8003-11e6-9483-3fd42e5d8735.png)

2016-09-21 13:52 UTC, alexduf approved these changes

2016-09-21 13:52 UTC, alexduf commented
:+1:

2016-09-21 15:11 UTC, alexduf approved these changes

2016-09-21 15:24 UTC, merged