Use a different thread pool for PayPal calls
guardian/contributions-frontend pull request #153
Opened 2016-09-26 14:19 UTC by pvighi

2016-09-26 14:37 UTC, alexduf commented on app/controllers/PaypalController.scala
> +      case Xor.Right(_) =>
I think this nested pattern match needs to be re-written as it gets hard to follow. I know it's not the point of this PR but that would be nice

2016-09-26 14:47 UTC, alexduf commented on app/services/PaypalService.scala
> +      links.find(_.getRel.equalsIgnoreCase("approval_url")).map(l => addUserActionParam(l.getHref))
I think you need to separate your concerns here. You're both searching for something and mapping on the value.

I would wrap only `payment.create(apiContext)` in the async block and start from there

2016-09-26 14:53 UTC, alexduf commented on app/services/PaypalService.scala
> +    val paymentResponse = asyncExecute(payment.execute(apiContext, paymentExecution)).value map {
If you want to map over the `Xor`, according to the doc you should be able to use [transform](http://typelevel.org/cats/api/index.html#cats.data.XorT@transform[C,D](f:cats.data.Xor[A,B]=%3Ecats.data.Xor[C,D])(implicitF:cats.Functor[F]):cats.data.XorT[F,C,D]) here like that:
```
asyncExecute(payment.execute(apiContext, paymentExecution)).transform {
  case Xor.Right(blah) => some Xor result
}
```

and then there's no need for your final `XorT(paymentResponse)`

2016-09-26 14:53 UTC, alexduf commented on app/services/PaypalService.scala
> +    XorT(res)
see comment below

2016-09-26 14:54 UTC, alexduf requested changes

2016-09-26 14:54 UTC, alexduf commented on app/controllers/PaypalController.scala
> +      case Xor.Right(_) =>
this one is optional, just nice to have

2016-09-26 16:11 UTC, pvighi commented on app/services/PaypalService.scala
> +    val paymentResponse = asyncExecute(payment.execute(apiContext, paymentExecution)).value map {
that is much better, I'll refactor it like that

2016-09-26 17:12 UTC, alexduf commented on app/services/PaypalService.scala
> +      case Xor.Right(createdPayment) => Xor.fromOption(getAuthLink(createdPayment), "No approval link returned from PayPal")
looking much better 👍

2016-09-26 17:13 UTC, alexduf commented on app/services/PaypalService.scala
> +  private def getAuthLink(payment: Payment) = {
[Optional] That would be nice to add Option[Uri] as the return type here

2016-09-27 08:50 UTC, pvighi commented on app/services/PaypalService.scala
> +  private def getAuthLink(payment: Payment) = {
I thought about that but I wasn't sure if we wanted to expose that Uri class on the public interface of the service.

2016-09-27 13:19 UTC, alexduf approved these changes
👍

2016-09-27 13:24 UTC, merged